version: 2
jobs:
  build_blah:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "build"
  test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: echo "test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_blah
      - test