version: 2
jobs:
  website:
    working_directory: ~/project/website
    docker:
      - image: hashicorp/middleman-hashicorp:0.3.35
    steps:
      - checkout:
          path: ~/project

      - run:
          name: bundler version
          command: bundle -v 
      
      #cache gems
      - restore_cache:
          key: alvintest-gems-v1-website-{{ checksum "Gemfile.lock" }}

      - run:
          command: bundle check || bundle install 
      
      - save_cache:
          key: alvintest-gems-v1-website-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/website/vendor/bundle
      
      # middleman build
      - run:
          command: pwd && ls -lah && echo "hello world" 

workflows:
  version: 2
  build-website:
    jobs:
      - website:
          filters:
            branches:
              only: stable-website
